[package]
name = "idgen-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.38"
rocket = "0.5.0-rc.2"
env_logger = "0.10.0"
